import type { Metadata } from "next";
import { Lato, Poppins } from "next/font/google";
import "./globals.css";
import { MainProvider } from "@/providers/main.provider";
import type { ReactNode } from "react";

const poppins = Poppins({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-poppins",
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const lato = Lato({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-lato",
	weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${lato.variable} ${poppins.variable} antialiased`}>
				<MainProvider>{children}</MainProvider>
			</body>
		</html>
	);
}
